version: '3'  # Specify the Docker Compose file format version

services:
  web:
    build: .  # Build the image from the Dockerfile in the current directory
    ports:
      - "9999:80"  # Map port 9999 on the host to port 80 in the container

